version: '3.3'
services:
   db:
     image: mariadb
     restart: always 
     hostname: mariadb
     container_name: mariadb
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     volumes:
       - /srv/docker/mysql:/var/lib/mysql
   wordpress:
     depends_on:
       - db
     image: nanih98/wordpress:5.5.1-apache-redis
     container_name: wordpress
     hostname: wordpress
     ports:
       - "80:80"
     restart: always
     volumes:
       - /srv/docker/html:/var/www/html
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
   redis:
     image: redis:5-alpine
     container_name: redis
     restart: always
     expose:
       - 6379
     #network_mode: host
     volumes:
       - /srv/redis/data:/data
     command: redis-server --appendonly yes --port 6379 --maxmemory 1gb --maxmemory-policy allkeys-lru #--requirepass "pruebas1234"
